### ISSUE TITLE
Title Case on thoughts

### ISSUE THREAD

**Issue by sgraha75** [FordLabs/retroquest#68]
#### What is the actual(incorrect) behavior?
The "Thought" and "Action Item" inputs are Title Casing (capitalizing every word) for all inputs

#### What is the expected(correct) behavior?
"Thought" and "Action Item" should show input as it is typed instead of capitalizing every word

#### Please provide your browser and OS versions:
Google Chrome on macOS 10.13.5

#### Include any logs/screenshots below:

![screen shot 2018-07-20 at 11 19 57 am](https://user-images.githubusercontent.com/40859026/43010601-e1525894-8c0e-11e8-8c83-abe3c492b8dd.png)

**Comment by abarna10** [comment]
Researching this issue, this bug is related to the recent styleguide changes (c4343e1613b6e85cea14f8c010a0941ad620e674).  The place holder text for the _Thought Entry_ and the _Action Item Entry_ is _enter a thought_ and _enter action item_ respectively, as observed in the following files: retroquest/ui/src/app/modules/teams/components/actions-header/actions-header.component.html and retroquest/ui/src/app/modules/teams/components/thoughts-header/thoughts-header.component.html .  In order to get this to be title case, the styleguide was altered to have _text-transform: capitalize_ in the following file: retroquest/ui/src/app/modules/controls/text-field/text-field.component.scss.

To resolve the issue, the .html files should be adjusted to be _Enter A Though_ and _Enter Action Item_ and the .scss file should be adjusted to be text-transformation: initial.  I will address these changes tomorrow and submit a corresponding Pull Request.

**Comment by sgraha75** [comment]
The changes related to this issue have been migrated to PROD.
